-- INSERT INTO `spacenow_stripe`.`AccCountryType` (`accCountryId`, `accTypeId`, `accFieldId`) VALUES ('1', '1', '1');
INSERT INTO `spacenow_stripe`.`AccCountryType` (`accCountryId`, `accTypeId`, `accFieldId`) VALUES ('1', '1', '2');
-- INSERT INTO `spacenow_stripe`.`AccCountryType` (`accCountryId`, `accTypeId`, `accFieldId`) VALUES ('1', '1', '3');
-- INSERT INTO `spacenow_stripe`.`AccCountryType` (`accCountryId`, `accTypeId`, `accFieldId`) VALUES ('1', '1', '4');
INSERT INTO `spacenow_stripe`.`AccCountryType` (`accCountryId`, `accTypeId`, `accFieldId`) VALUES ('1', '1', '5');
INSERT INTO `spacenow_stripe`.`AccCountryType` (`accCountryId`, `accTypeId`, `accFieldId`) VALUES ('1', '1', '6');
INSERT INTO `spacenow_stripe`.`AccCountryType` (`accCountryId`, `accTypeId`, `accFieldId`) VALUES ('1', '1', '7');
-- INSERT INTO `spacenow_stripe`.`AccCountryType` (`accCountryId`, `accTypeId`, `accFieldId`) VALUES ('1', '1', '8');
-- INSERT INTO `spacenow_stripe`.`AccCountryType` (`accCountryId`, `accTypeId`, `accFieldId`) VALUES ('1', '1', '9');
INSERT INTO `spacenow_stripe`.`AccCountryType` (`accCountryId`, `accTypeId`, `accFieldId`) VALUES ('1', '1', '10');
INSERT INTO `spacenow_stripe`.`AccCountryType` (`accCountryId`, `accTypeId`, `accFieldId`) VALUES ('1', '1', '11');