// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const AWS_CONFIG =  {
    AWS_APPSYNC: {
        STRIPE_ACC: {
            GRAPHQL_ENDPOINT: "https://nojthrakrzegpibfmrilroc7g4.appsync-api.us-east-1.amazonaws.com/graphql",
            REGION: "us-east-1",
            AUTH_TYPE: "API_KEY",
            API_KEY: "da2-drnr67ksufaw5odaipi3vhbe74"
        }
    },
    AWS_API_GATEWAY: {
        STRIPE: {
            API_URL: "https://nl2wuwhaqc.execute-api.ap-southeast-2.amazonaws.com/dev/"
        }
    }
};